# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bda65f65337755de083ba67811bc02be1a16fe6be510303ed8f93995cc7a18ade293c6297828dc637437a9820f7e666998d8a89761d323a16b79e648f8c36c35

test:
  secret_key_base: 6513877010b766e22e0266a61d304f9fc7db4af2c2c0fd3e61f010fe284a2895322b00efc42adc2893276215eda989138d5f052b1ba8c14c2e6fc89df1783ae3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
